//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YBF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YBF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 try {
        ///	//收集字体
        ///	 var fontArray=new Array();
        ///	for ( i = 0; i&lt; app.textFonts.length; i++) 	
        ///	{
        ///		fontArray[i]=app.textFonts[i].family;
        ///	}
        ///		var doc=app.open(new File(&apos;*文件名*&apos;));
        ///		//判断字体
        ///		for ( i = 0; i&lt; doc.textFrames.length; i++) 
        ///		{
        ///			var avFont=app.activeDocument.textFrames[i].textRange.characterAttributes.textFont.family;
        ///			var isExist=0;
        ///			for ( j = 0; j&lt; fontArray.length; j++) 
        ///			{
        ///				if(avFont==fontArray[j])
        ///				{
        ///					isExist=1;
        ///					break;
        ///				}
        ///			}
        ///			if(isExist==0)
        ///			{ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AutoSavePdf {
            get {
                return ResourceManager.GetString("AutoSavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var doc=app.documents.add();
        ///	var tf=doc.textFrames.add();
        ///	tf.contents=&quot;测试成功! *当前时间*&quot;;
        ///	tf.left=0;
        ///	tf.top=doc.height/2;
        ///	newCMYKColor = new CMYKColor();
        ///	newCMYKColor.black = 0;
        ///	newCMYKColor.cyan = 0;
        ///	newCMYKColor.magenta = 100;
        ///	newCMYKColor.yellow = 100;
        ///	for(i=0;i&lt;tf.characters.length;i++)
        ///	{
        ///		tf.characters[i].characterAttributes.size=40;
        ///		tf.characters[i].fillColor = newCMYKColor;
        ///	} 的本地化字符串。
        /// </summary>
        public static string IllustratorTest {
            get {
                return ResourceManager.GetString("IllustratorTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        ///&lt;JDF xmlns=&quot;http://www.CIP4.org/JDFSchema_1_1&quot; ID=&quot;*GUID_000*&quot; JobID=&quot;*文件名称*&quot; JobPartID=&quot;*文件名称*&quot; xmlns:SSi=&quot;http://www.creo.com/SSI/JDFExtensions.xsd&quot; SSi:PrepsGenerated=&quot;1&quot; Status=&quot;Ready&quot; Type=&quot;ProcessGroup&quot; Version=&quot;1.2&quot;&gt;
        ///
        ///  &lt;JDF ID=&quot;*GUID_001*&quot; JobPartID=&quot;*文件名称*&quot; Status=&quot;Waiting&quot; Type=&quot;Imposition&quot;&gt;
        ///    &lt;ResourceLinkPool&gt;
        ///      &lt;LayoutLink Usage=&quot;Input&quot; rRef=&quot;*GUID_002*&quot;/&gt;
        ///      &lt;RunListLink ProcessUsage=&quot;Document&quot; Usage=&quot;Input&quot; rRef=&quot;*GUID_003 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string JdfTemplate {
            get {
                return ResourceManager.GetString("JdfTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT OID ID,
        ///PLTSTS 审核,
        ///BCPSTS 甩纸,
        ///SPCSHW 稿袋号,
        ///MACNME 设备,
        ///SMPNME 客户,
        ///prdnme 产品,
        ///ssizew||&apos;x&apos;||ssizel 面纸尺寸, 
        ///DECODE( PRDTYP,&apos;ST&apos;,&apos;新版&apos;,&apos;SU&apos;,&apos;旧版&apos;,&apos; &apos;)版类,
        ///SPCNUM 专色,
        ///COLNUM 颜色,
        ///COLSUM 版数量,
        ///to_char( SHDATE, &apos;yyyy-mm-dd&apos; ) 交期,
        ///CTTECHES 要求
        ///
        ///FROM EJSH.V_ORD_SCH 
        ///WHERE  ORGCDE=&apos;KS03&apos; and OBJTYP=&apos;CL&apos;and OSTATUS=&apos;Y&apos; AND status IN (&apos;2&apos;,&apos;3&apos;,&apos;4&apos;)  AND PRCTYPNME=&apos;胶印凹印&apos; 的本地化字符串。
        /// </summary>
        public static string SQLYijie {
            get {
                return ResourceManager.GetString("SQLYijie", resourceCulture);
            }
        }
    }
}
